// Generated by IcedCoffeeScript 1.8.0-d
(function() {
  var lookup_tab, proofs, web_service;

  web_service = require('./web_service');

  proofs = require('keybase-proofs');

  lookup_tab = {
    "test.web_service_binding.rooter": web_service.RooterBinding
  };

  exports.alloc = function(type, args) {
    return proofs.alloc(type, args, lookup_tab);
  };

}).call(this);
