// Generated by IcedCoffeeScript 1.8.0-d
(function() {
  var constants, d, k, kbp, v, _ref, _ref1;

  kbp = require('keybase-proofs');

  exports.constants = constants = {
    proof_types: {
      rooter: 100001
    }
  };

  d = {};

  _ref = constants.proof_types;
  for (k in _ref) {
    v = _ref[k];
    d[v] = k;
  }

  _ref1 = kbp.constants.proof_types;
  for (k in _ref1) {
    v = _ref1[k];
    d[v] = k;
  }

  exports.proof_type_to_string = d;

}).call(this);
